### ISSUE TITLE
when deploy to kuberntes，encounter IndexAlreadyExists error

### ISSUE THREAD

**Issue by xinmans** [zlib-searcher/zlib-searcher#54]
[2022-12-31T14:42:22Z INFO  zlib_searcher] zlib-searcher webserver started!
[2022-12-31T14:42:22Z INFO  zlib_searcher] AppState init!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndexAlreadyExists', /source/crates/zlib-searcher-core/src/lib.rs:120:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace、

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yml
    kompose.service.type: NodePort
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: zlib
  name: zlib
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zlib
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-k8s.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: zlib
    spec:
      containers:
        - image: ghcr.io/zlib-searcher/zlib-searcher:master
          name: zlib-searcher
          ports:
            - containerPort: 7070
          resources: {}
          volumeMounts:
            - mountPath: /index
              name: zlib-volume
      restartPolicy: Always
      volumes:
        - name: zlib-volume
          hostPath:
            path: /mydev/zlib-searcher/index
            type: DirectoryOrCreate
status: {}

project/zlib-searcher/zlib-deployment.yaml

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yml
    kompose.service.type: NodePort
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: zlib-tcp
  name: zlib-tcp
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
  selector:
    io.kompose.service: zlib
  type: NodePort
status:
  loadBalancer: {}
project/zlib-searcher/zlib-tcp-service.yaml

**Comment by bolshoytoster** [comment]
It looks like this is caused by this block:
https://github.com/zlib-searcher/zlib-searcher/blob/da1e8c7fd615ce4971f0d148fa4bb5fd5229e12a/crates/zlib-searcher-core/src/lib.rs#L118-L121

A bit complicated, but broken down:
- `Index::open_in_dir(index_dir)`
  Tries to open an index if it exists, returns an `Err` if not.
- `unwrap_or_else`
  'Catches' an error if returned and runs the given function.
- `std::fs::create_dir_all(index_dir)`
  Assumes that the error is because of the index not existing, makes sure the directory exists.
-  `Index::create_in_dir(index_dir, schema.clone())`
  (This is where the error comes from)
  Tries to create a new index, and in this case, fails because it already exists.

The problem is because this assumes that `Index::open_in_dir` can only fail because of an index not existing, but it can also fail for:
- Failing to parse `meta.json`
- Generic IO errors
- Incompatible versions (although not possible at the time of writing)
- Non-utf-8 data in `meta.json`

The solution is probably just to check that the error is what you expect it is:
```rust
        let mut index = Index::open_in_dir(index_dir).unwrap_or_else(|err| {
            if let TantivyError::OpenDirectoryError(_) = err {
                std::fs::create_dir_all(index_dir).expect("create index directory");
                Index::create_in_dir(index_dir, schema.clone()).unwrap()
            } else {
                panic!("Error opening index: {err:?}");
            }
        });
```
I've opened a PR with this change: #61
